### ISSUE TITLE
关于环境部署在虚拟机中~

### ISSUE THREAD

**Issue by aqiansunboy** [dongweiming/wechat-admin#1]
我在虚拟机中部署了环境，并用虚拟机的IP访问

http://192.168.33.10:8100/#/login

可以看到页面“Scan to log in to WeChat”，但二维码显示不了。并且报一些列错：

GET http://localhost:8100/stream net::ERR_CONNECTION_REFUSED
app.js:1 Failed to connect to event stream
localhost:8100/stream:1 GET http://localhost:8100/stream net::ERR_CONNECTION_REFUSED
app.js:1 Failed to connect to event stream
localhost:8100/stream:1 GET http://localhost:8100/stream net::ERR_CONNECTION_REFUSED
app.js:1 Failed to connect to event stream
localhost:8100/stream:1 GET http://localhost:8100/stream net::ERR_CONNECTION_REFUSED
app.js:1 Failed to connect to event stream

之类的错误。请问这种情况如何解决呢？我虚拟机是全控制台的，并没有浏览器去访问localhost的条件。

谢谢~

**Comment by dongweiming** [comment]
你要修改API_URL的设置 修改成http://192.168.33.10:8100。或者设置正确的端口转发
