### ISSUE TITLE
"ImportError: cannot import name Celery" and "NameError: global name 'FileNotFoundError' is not defined"

### ISSUE THREAD

**Issue by wave52** [dongweiming/wechat-admin#10]
登陆后报错：NameError: global name 'FileNotFoundError' is not defined，
启动Celery Beat和Worker：ImportError: cannot import name Celery

**Comment by dongweiming** [comment]
你用的什么版本？这个项目只支持Python 3哦。另外是否执行了`venv/bin/pip install -r requirements.txt`?

**Comment by wave52** [comment]
确实是版本的问题，已解决
