### ISSUE TITLE
登录页面不停刷新，产生close wait连接，堵死server进程

### ISSUE THREAD

**Issue by zgjhust** [dongweiming/wechat-admin#11]
1. 在登录页面不停刷新，浏览器到server的连接中断，但是server未能及时关闭连接，最后导致gunicorn被堵死，只能重启，没想到好的解决办法～
![2017-07-21 10 33 56](https://user-images.githubusercontent.com/1053305/28446895-46332456-6e00-11e7-8264-b2e6aa8c576d.png)

2. flask app默认只能处理一个并发，可以做如下修改，方便调试
```
if __name__ == '__main__':                                                                                                                         
     app.run(host='0.0.0.0', port=8100, debug=app.debug, threaded=True)
```

**Comment by dongweiming** [comment]
嗯，有可能。由于我在用gunicorn的时候使用了`-t 0`也就是为了不超时。这样设置超时时间的原因是项目中的sse需要一个长连接，而且从用户打开登录页面到扫码完成这个时间不好控制，就索性不超时了。感谢，我在README里面说明一下
