### ISSUE TITLE
使用docker-compose build出错

### ISSUE THREAD

**Issue by aleonchen** [dongweiming/wechat-admin#15]
`COPY models libs static templates uploads wechat-plugins views wechat *.py requirements.txt local_settings.py.tmpl /web/`

代码缺少uploads 和 wechat-plugins 这两个目录，自己创建就好了
建议加上

**Comment by dongweiming** [comment]
好的，我加上wechat-plugins，不过我看uploads目录现在已经有了呢？ @aleonchen

**Comment by guyskk** [comment]
刚试了下第一次运行没有 uploads 目录

**Comment by dongweiming** [comment]
我当时设计的是会自动创建这个目录， https://github.com/dongweiming/wechat-admin/blob/af1f7bc1f1b7ce5bfb57d7c95984cf2a7c2527ce/config.py#L51 难道没生效么？

**Comment by dongweiming** [comment]
呃呃，我突然懂了
