### ISSUE TITLE
打开网页后，二维码以外部文件跳出来，扫描后也无法登陆，有遇到这种情况的吗

### ISSUE THREAD

**Issue by wzyonggege** [dongweiming/wechat-admin#17]

**Comment by wzyonggege** [comment]
redis忘记开了

**Comment by dongweiming** [comment]
@wzyonggege  好，「二维码以外部文件跳出来」是itchat的默认实现，会尝试直接打开这个文件，
 https://github.com/dongweiming/ItChat/blob/0cc39825912b7d0e7f56bec881590fd0c3a20aa4/itchat/utils.py#L81
