### ISSUE TITLE
commit #1de18cc  base64二维码图片显示问题

### ISSUE THREAD

**Issue by zgjhust** [dongweiming/wechat-admin#18]
如下修改导致登录时加载二维码失败

```
# wechat.js eventSourceListener
self.qrCode = `data:image/png;base64,${data.extra}`; 
```

![2017-07-26 5 42 08](https://user-images.githubusercontent.com/1053305/28615412-8c021116-722b-11e7-916e-7321396a6920.png)

**Comment by dongweiming** [comment]
@zgjhust 嗯，一个不兼容的修改，需要重新重新安装itchat：

```python
pip install -e git+https://github.com/dongweiming/ItChat@signals#egg=itchat
```

**Comment by dongweiming** [comment]
修改在这里。 https://github.com/dongweiming/ItChat/commit/a70304bd3f1fdc18e9e1572269c55a0413457faf

**Comment by zgjhust** [comment]
thanks！ @dongweiming
