### ISSUE TITLE
扫码图片无法显示，查看元素发现url host 居然是localhost，而不是主机ip

### ISSUE THREAD

**Issue by cxgreat2014** [dongweiming/wechat-admin#26]
我主机的ip是45.xxx.xxx.xxx,访问url是http://45.xxx.xxx.xxx:8100/#/login
然而二维码图片url是http://localhost:8100/static/img/qr_code.gif
修复一下

**Comment by cxgreat2014** [comment]
好吧。。刚刚看到另外一个人和我差不多的issue，为啥要手动设置API_URL，而不是通过访问链接自动设置API_URL呢？

**Comment by dongweiming** [comment]
请仔细阅读README

**Comment by dongweiming** [comment]
这是一个前后端分离的项目，前端会打包到一起，生成一个目标文件被引用。你就需要打包前修改API_URL
