### ISSUE TITLE
build 失败日志

### ISSUE THREAD

**Issue by xxl-xxl** [dongweiming/wechat-admin#27]
0 info it worked if it ends with ok
1 verbose cli [ '/opt/node/bin/node', '/opt/node/bin/npm', 'run', 'build' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle wechat-vue-admin@1.0.0~prebuild: wechat-vue-admin@1.0.0
6 info lifecycle wechat-vue-admin@1.0.0~build: wechat-vue-admin@1.0.0
7 verbose lifecycle wechat-vue-admin@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle wechat-vue-admin@1.0.0~build: PATH: /opt/node/lib/node_modules/npm/bin/node-gyp-bin:/root/wechat-admin/node_modules/.bin:/opt/node/bin:/usr/local/php/sbin:/usr/local/php/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle wechat-vue-admin@1.0.0~build: CWD: /root/wechat-admin
10 silly lifecycle wechat-vue-admin@1.0.0~build: Args: [ '-c', 'node build/build.js' ]
11 silly lifecycle wechat-vue-admin@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle wechat-vue-admin@1.0.0~build: Failed to exec build script
13 verbose stack Error: wechat-vue-admin@1.0.0 build: `node build/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/opt/node/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/opt/node/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid wechat-vue-admin@1.0.0
15 verbose cwd /root/wechat-admin
16 verbose Linux 2.6.32-431.23.3.el6.x86_64
17 verbose argv "/opt/node/bin/node" "/opt/node/bin/npm" "run" "build"
18 verbose node v8.2.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error wechat-vue-admin@1.0.0 build: `node build/build.js`
22 error Exit status 1
23 error Failed at the wechat-vue-admin@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by xxluan** [comment]
现在扫码默认的图片url是http://localhost:8100/static/img/qr_code.gif
我要把localhost改掉，但是在 npm run build 就出现错误日志

**Comment by xxl-xxl** [comment]
配置前端开发环境，安装需要的包，就可以build了 。
