### ISSUE TITLE
npm run build 成功，启动服务，访问web是空白

### ISSUE THREAD

**Issue by xxl-xxl** [dongweiming/wechat-admin#28]
修改了webpack.prod.conf.js 的API_URL为服务器外网ip。
进行npm run build 成功，启动服务，访问web是空白。
发现static目录里只有 emoji和img两个目录，请问是什么问题？

**Comment by xxl-xxl** [comment]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='login.weixin.qq.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))

You can't get access to internet or wechat domain, so exit.

是不是微信那边限制了接口？

**Comment by dongweiming** [comment]
如果static目录里只有 emoji和img两个目录，肯定是你build没有成功，你可以把整个过程截下来让我看看

连接微信的错误你要自己解决，我的是正常的

**Comment by dongweiming** [comment]
你用的虚拟机吧.... buildJ进程占用内存过多被杀死了的感觉

**Comment by xxl-xxl** [comment]
阿里云服务器。那我该怎么办？

**Comment by xxl-xxl** [comment]
是内存问题，解决了。谢谢解答。
