### ISSUE TITLE
登录二维码不出现 console二维码扫码死循环

### ISSUE THREAD

**Issue by kengxin** [dongweiming/wechat-admin#33]
登陆的二维码不出现。console里面的二维码 扫码之后 web二维码会出现 随后点击登录卡死，页面不跳转，刷新页面console又出现一个二维码，随后死循环操作 登录不上去

**Comment by kengxin** [comment]
![image](https://user-images.githubusercontent.com/18631708/29067047-cc0ab992-7c63-11e7-9fef-f7fb068ad1e8.png)
![image](https://user-images.githubusercontent.com/18631708/29067054-d3f9bb94-7c63-11e7-8b49-dcde8aebbb5f.png)

**Comment by JUJUStar** [comment]
我也是这个情况，在服务器上会这样，本地的话则不会

**Comment by dongweiming** [comment]
@kengxin @JUJUStar 如果正确的改了API_URL并且执行了npm run build重新生成静态文件并上传到服务器会这样，就很奇怪。你可以删掉*.pkl文件，重启进程试一试。略奇怪。
另外可以打开chrome的console看看报什么错误发给我？
