### ISSUE TITLE
群内消息互相转发

### ISSUE THREAD

**Issue by zhenzhang20** [dongweiming/wechat-admin#34]
是否可以考虑加入转发功能
定制哪几个群内容互相转发。如：群1，群2， 群3 ， 那么三个中任何一个群中用户发的文本、图片、语音、视频，可以自动通过机器人转发到其他两个群，实现消息互通

谢谢

**Comment by dongweiming** [comment]
这种定制需要你可以来贡献代码呀~ 欢迎
