### ISSUE TITLE
微信中已经存在20多个群，但目前只读取和更新了10个。不知道这个是在哪里做限制了。

### ISSUE THREAD

**Issue by dockersky** [dongweiming/wechat-admin#40]

**Comment by dongweiming** [comment]
我看代码使用了Itchat的 [get_chatrooms](https://github.com/littlecodersh/ItChat/blob/0cc39825912b7d0e7f56bec881590fd0c3a20aa4/itchat/components/contact.py#L309), 并没有特殊的指定参数。不过我的微信里面群很少，没法验证你说的这个问题，你可以去ItChat里面问问，或者用网页版微信登录看看全部群都能列出来么，试着调试下ItChat的源码，说不定能给它贡献个PR

**Comment by Wangjunyu** [comment]
因为是网页版的扩展,所以只有近期有互动的群的信息才会在网页版体现.
