### ISSUE TITLE
终端页面点击“退出登录”无效

### ISSUE THREAD

**Issue by wunifeng** [dongweiming/wechat-admin#46]
软硬件环境：ubuntu 14.04，python3.4，VPS 远程连接， firefox终端。
点击“退出登录”，页面返回扫码页面，马上又自动进入主页面，再点击“退出登录”，再次返回扫码页面并马上进入主页面，直到第三次点击“退出登录”返回扫码界面之后，页面并没有返回主页面，但是服务端没有打印出“logout”消息

**Comment by dongweiming** [comment]
点退出登录进入扫码页面，马上又自动进入主页面确实是现在的实现方案。自动登录是由于后端的token记录了之前的登录信息，微信返回状态不需要扫码就直接登录造成的。由于本项目没想着商用，所以不考虑多用户场景，退出登录这个按钮有些鸡肋了

我修一下
