### ISSUE TITLE
是否能提供docker的解决方案

### ISSUE THREAD

**Issue by Gcaufy** [dongweiming/wechat-admin#5]
后端安装起来貌似还是挺复杂的，能否提供docker支持？

**Comment by dongweiming** [comment]
@Gcaufy 可以的。现在还是最后的开发调试过程中，等稳定之后会提供docker版本的。这个issue可以先留着

**Comment by dongweiming** [comment]
@Gcaufy 已经支持啦。可以README中的说明：https://github.com/dongweiming/wechat-admin#使用docker
