### ISSUE TITLE
手机微信扫码后，手机页面一直提示“暂时无法登录,请重新尝试登录”

### ISSUE THREAD

**Issue by aqiansunboy** [dongweiming/wechat-admin#6]
如题~

![default](https://user-images.githubusercontent.com/6840638/28299369-5f0a490c-6bab-11e7-907c-c05485929357.png)

**Comment by dongweiming** [comment]
咦  从来没遇到过~ 你可以删除*.pkl文件，清除数据库数据重新按照README里面说的试一次？

**Comment by aqiansunboy** [comment]
不行呀，试过了。我第一次是可以。后来退出换了个账号后就不行了。奇怪~是被微信封了吗？

**Comment by aqiansunboy** [comment]
微信报`查找失败(4,-1)`的Toast提示~

**Comment by aqiansunboy** [comment]
奇怪，我从头到尾重新执行了一遍后，就可以了。这是不是你们的Bug呀~

**Comment by aqiansunboy** [comment]
我网页退出登录后，此问题又出现~

**Comment by dongweiming** [comment]
@aqiansunboy 你可以拉最新的代码试验下？我昨晚改了itchat的实现

**Comment by dongweiming** [comment]
如果还有整个你再打开这个issue

**Comment by aqiansunboy** [comment]
@dongweiming 好的，谢谢~我再试下

**Comment by aqiansunboy** [comment]
@dongweiming 
![image](https://user-images.githubusercontent.com/6840638/28510418-d9a8c386-707a-11e7-82f7-9285006f590a.png)

**Comment by aqiansunboy** [comment]
@dongweiming 拉取最新的代码后，重新编译，运行，显示不了二维码。前端和后端亦无任何报错。

**Comment by dongweiming** [comment]
@aqiansunboy 强制刷新页面？ 另外依赖要重新装

**Comment by aqiansunboy** [comment]
@dongweiming 噢噢，依赖我没重装。再试下~
