### ISSUE TITLE
获取两三次二维码后，服务访问不上去了

### ISSUE THREAD

**Issue by aqiansunboy** [dongweiming/wechat-admin#9]
持续出现二维码扫描报`查找失败(4,-1)`的错误，并且，刷新登录页以重新获取二维码，刷新两到三次后，服务器就连接不上了。关闭服务并重新执行：

```bash
 venv/bin/gunicorn app:app --bind 192.168.33.10:8100 -w 4 -t 0
```

才能继续访问登录页。同样，直接刷新页面两到三次后，继续访问不了了。

![刷新页面两三次后，页面就一直处于连接状态中](https://user-images.githubusercontent.com/6840638/28310875-6b76e03a-6be0-11e7-893d-b800491717a4.png)

**Comment by dongweiming** [comment]
@aqiansunboy 我在README解释了这个问题 https://github.com/dongweiming/wechat-admin#为什么用着用着有时候感觉卡住了接口不返回了，本地的话使用`python app.py`，如果使用gunicorn的话先加大Worker数量
